name: STM32 Bug Report
description: Report a bug or issue with STM32 platform support
title: "[STM32] "
labels: ["bug", "stm32", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report for STM32 platform support!
        
        Please provide as much detail as possible to help us reproduce and fix the issue.

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      description: Please verify these items before submitting the bug report
      options:
        - label: I have searched existing issues and this is not a duplicate
          required: true
        - label: I have tested with the latest version of FluidNC
          required: true
        - label: I have tried building offline using `./build-offline.sh`
          required: false
        - label: I have checked the build system documentation
          required: false

  - type: dropdown
    id: stm32_board
    attributes:
      label: STM32 Board
      description: Which STM32 board or configuration are you using?
      options:
        - STM32F103C8 (stm32_noradio)
        - STM32F401CC (stm32_basic)
        - STM32F407VG (stm32_advanced)
        - Custom STM32 board
        - Unknown/Not sure
      default: 0
    validations:
      required: true

  - type: dropdown
    id: build_environment
    attributes:
      label: Build Environment
      description: Which build environment are you using?
      options:
        - stm32_noradio
        - stm32_basic
        - stm32_advanced
        - Custom environment
      default: 0
    validations:
      required: true

  - type: dropdown
    id: operating_system
    attributes:
      label: Operating System
      description: Which operating system are you using?
      options:
        - Windows
        - macOS
        - Linux (Ubuntu/Debian)
        - Linux (Other)
        - Other
      default: 0
    validations:
      required: true

  - type: textarea
    id: bug_description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: expected_behavior
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen
      placeholder: What should have happened...
    validations:
      required: true

  - type: textarea
    id: actual_behavior
    attributes:
      label: Actual Behavior
      description: A clear and concise description of what actually happened
      placeholder: What actually happened...
    validations:
      required: true

  - type: textarea
    id: reproduction_steps
    attributes:
      label: Steps to Reproduce
      description: Detailed steps to reproduce the issue
      placeholder: |
        1. Go to '...'
        2. Run command '...'
        3. See error
    validations:
      required: true

  - type: textarea
    id: build_output
    attributes:
      label: Build Output
      description: If this is a build issue, please provide the complete build output
      placeholder: |
        ```
        Paste build output here...
        ```
      render: shell

  - type: textarea
    id: runtime_logs
    attributes:
      label: Runtime Logs
      description: If this is a runtime issue, please provide serial monitor output
      placeholder: |
        ```
        Paste serial monitor output here...
        ```
      render: shell

  - type: textarea
    id: configuration
    attributes:
      label: Configuration
      description: Please provide your configuration (platformio.ini changes, config.yaml, etc.)
      placeholder: |
        ```yaml
        # Your configuration here
        ```
      render: yaml

  - type: textarea
    id: hardware_info
    attributes:
      label: Hardware Information
      description: Details about your hardware setup
      placeholder: |
        - STM32 board: [Board name and version]
        - Programmer: [ST-Link, USB, etc.]
        - Connected peripherals: [Motors, sensors, etc.]
        - Power supply: [Voltage, current rating]

  - type: textarea
    id: network_environment
    attributes:
      label: Network Environment
      description: If this is a network/firewall related issue, please provide details
      placeholder: |
        - Network type: [Corporate, Home, Public]
        - Firewall: [Yes/No, Type]
        - Proxy: [Yes/No, Configuration]
        - DNS: [Default, Custom]
        - Offline build attempted: [Yes/No]

  - type: textarea
    id: additional_context
    attributes:
      label: Additional Context
      description: Add any other context about the problem here
      placeholder: Any additional information that might help...

  - type: markdown
    attributes:
      value: |
        ## Debug Information
        
        Please also run the following commands and include the output:
        
        ```bash
        # System information
        pio system info
        
        # Platform information
        pio platform list
        
        # Build with verbose output
        pio run -e stm32_noradio -v
        
        # Network diagnostics (if applicable)
        curl -I https://api.registry.platformio.org/
        ```